project:
  type: website
  output-dir: docs

website:
  # title: 
  navbar:
    # logo: Kathleen & Wai
    right:
      # - href: index.qmd
      #   text: Home
      - href: https://www.google.com/maps?cid=6769603451629656288&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYASAA&hl=en&gl=US&source=embed
        text: Location
        target: _blank
      - text: Registry
        menu:
          - text: Amazon
            href: https://www.amazon.com
            target: _blank
      - href: index.qmd#catering
        text: Catering
      - href: index.qmd#faqs
        text: FAQs
      - href: index.qmd#contact
        text: Contact
    search: false
    pinned: true
    toggle-position: right
  announcement:
    dismissable: true
    content: "Have you RSVP'ed to our wedding yet? If not please do so by XX.XX.XX!"
    type: warning
    position: above-navbar

format:
  html:
    theme: [wpkn_mat.scss]
    page-layout: full
    # css: styles.css
    # grid:
      # sidebar-width: 100px
      # body-width: 800px
      # margin-width: 100px
      # gutter-width: 1.5rem
    smooth-scroll: true



